# Generated by Django 5.2.1 on 2025-08-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_profile_mentor_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorEligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('min_followers', models.IntegerField(default=0)),
                ('min_posts', models.IntegerField(default=0)),
                ('post_streak_window_days', models.IntegerField(default=0)),
                ('min_account_age_months', models.IntegerField(default=0)),
                ('min_avg_engagement', models.FloatField(default=0)),
                ('require_verified_profile', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('post_streak_window_days', models.IntegerField(default=90)),
                ('min_account_age_months', models.PositiveIntegerField(default=0)),
                ('avg_engagement', models.FloatField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_eligibility', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('specializations', models.TextField(help_text='Art styles/techniques mentor specializes in')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('max_mentees', models.PositiveIntegerField(default=5)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_accepting_requests', models.BooleanField(default=True)),
                ('total_mentees', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
