# Generated by Django 5.2.1 on 2025-06-09 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_remove_organization_visibility_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/logos/')),
                ('visibility_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='profiles.profile')),
                ('friends', models.ManyToManyField(blank=True, to='profiles.profile')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organization.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('date', 'Date')], default='text', max_length=10)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='profile_fields/images/')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='profile_fields/files/')),
                ('date_value', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='profiles.profile')),
            ],
            options={
                'ordering': ['profile', 'display_order', 'field_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('organization__isnull', True)), models.Q(('user__isnull', True), ('organization__isnull', False)), _connector='OR'), name='only_one_profile_target'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization',), name='unique_organization_profile'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_profile', 'to_profile'], name='profiles_fr_from_pr_601770_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['status'], name='profiles_fr_status_7a59eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_profile', 'to_profile')},
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'field_name'], name='profiles_pr_profile_af4cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'display_order'], name='profiles_pr_profile_2033e8_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'is_public'], name='profiles_pr_profile_38d33e_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['field_type'], name='profiles_pr_field_t_bff8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['text_value'], name='profiles_pr_text_va_3b580c_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['date_value'], name='profiles_pr_date_va_6bbb13_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile', 'field_name'), name='unique_profile_field_name'),
        ),
    ]
