# Generated by Django 5.2.1 on 2025-07-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='artserviceinquiry',
            name='artist_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_service_inquiries', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='artserviceinquiry',
            name='inquirer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_art_inquiries', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='artservice',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_service', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilecanvas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilecanvas',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_canvas', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilefieldsection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilefieldsection',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sections', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='profiles.profilefieldsection'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_field_responses', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='static_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='profiles.staticprofilefield'),
        ),
        migrations.AddField(
            model_name='staticprofilefield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='profiles.staticprofilesection'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='profile_username_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['bio'], name='profile_bio_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['tools'], name='profile_tools_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['awards'], name='profile_awards_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('organization__isnull', True)), models.Q(('user__isnull', True), ('organization__isnull', False)), _connector='OR'), name='only_one_profile_target'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization',), name='unique_organization_profile'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_profile', 'to_profile'], name='profiles_fr_from_pr_601770_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['status'], name='profiles_fr_status_7a59eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_profile', 'to_profile'), name='unique_pending_friend_request'),
        ),
        migrations.AlterUniqueTogether(
            name='artserviceinquiry',
            unique_together={('artist_profile', 'inquirer_profile')},
        ),
        migrations.AddIndex(
            model_name='profilecanvas',
            index=models.Index(fields=['profile'], name='profiles_pr_profile_a2f64e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilefieldsection',
            unique_together={('profile', 'title')},
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'field_name'], name='profiles_pr_profile_af4cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'display_order'], name='profiles_pr_profile_2033e8_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['profile', 'is_public'], name='profiles_pr_profile_38d33e_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['field_type'], name='profiles_pr_field_t_bff8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['text_value'], name='profiles_pr_text_va_3b580c_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['date_value'], name='profiles_pr_date_va_6bbb13_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile', 'field_name'), name='unique_profile_field_name'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['profile', 'viewed_at'], name='profiles_pr_profile_1b3e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profileview',
            unique_together={('viewer', 'profile')},
        ),
        migrations.AddIndex(
            model_name='staticfieldvalue',
            index=models.Index(fields=['profile', 'static_field'], name='profiles_st_profile_5d418c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staticfieldvalue',
            unique_together={('profile', 'static_field')},
        ),
    ]
