# Generated by Django 5.2.1 on 2025-08-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentor_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_eligibile',
            field=models.BooleanField(default=False),
        ),
    ]
