# Generated by Django 5.2.1 on 2025-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_logo_profile_picture_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('user', 'User')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
