# Generated by Django 5.2.1 on 2025-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_mentor_blacklisted_profile_mentor_eligibile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentor_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
