# Generated by Django 5.2.1 on 2025-06-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_picture_profile_cover_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFieldSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sections', to='profiles.profile')),
            ],
            options={
                'ordering': ['profile', 'display_order'],
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
