# Generated by Django 5.2.1 on 2025-06-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilefieldsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='profiles.profilefieldsection'),
        ),
    ]
