# Generated by Django 5.2.1 on 2025-06-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefield_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefieldsection',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='profilefieldsection',
            unique_together={('profile', 'title')},
        ),
    ]
