# Generated by Django 5.2.1 on 2025-06-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profilefieldsection_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='profiles.profilefieldsection'),
        ),
    ]
