# Generated by Django 5.2.1 on 2025-07-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_city_profile_country_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticfieldvalue',
            old_name='field_value',
            new_name='text_value',
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='static_fields/files/'),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to='static_fields/images/'),
        ),
        migrations.AddField(
            model_name='staticfieldvalue',
            name='number_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staticprofilefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('image', 'Image'), ('file', 'File'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('boolean', 'Boolean'), ('textarea', 'Textarea')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='staticprofilefield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
