# Generated by Django 5.2.1 on 2025-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notify_email',
        ),
    ]
