# Generated by Django 5.2.1 on 2025-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_notify_email_profile_view_count_profileview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileview',
            unique_together={('viewer', 'profile')},
        ),
    ]
