# Generated by Django 5.2.1 on 2025-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_notify_email'),
        ('profiles', '0021_alter_profileview_unique_together'),
    ]

    operations = [
    ]
