# Generated by Django 5.2.1 on 2025-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profilefield_last_active_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefield',
            name='last_active_at',
        ),
        migrations.RemoveField(
            model_name='profilefield',
            name='last_reminder_sent_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
