# Generated by Django 5.2.1 on 2025-07-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_profilefield_last_active_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='art_service_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ArtService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('service_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing', models.TextField(blank=True, null=True)),
                ('specialties', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_hours', models.TextField(blank=True, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepts_rush_orders', models.BooleanField(default=False)),
                ('offers_consultations', models.BooleanField(default=True)),
                ('offers_revisions', models.BooleanField(default=True)),
                ('max_revisions', models.PositiveIntegerField(blank=True, null=True)),
                ('client_testimonials', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('total_projects_completed', models.PositiveIntegerField(default=0)),
                ('response_time_hours', models.PositiveIntegerField(default=24)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_service', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Art Service',
                'verbose_name_plural': 'Art Services',
            },
        ),
        migrations.CreateModel(
            name='ArtServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_notified', models.BooleanField(default=False)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_service_inquiries', to='profiles.profile')),
                ('inquirer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_art_inquiries', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('artist_profile', 'inquirer_profile')},
            },
        ),
    ]
