# Generated by Django 5.2.1 on 2025-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_profile_art_service_enabled_artservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_mentions',
            field=models.BooleanField(default=True),
        ),
    ]
