# Generated by Django 5.2.1 on 2025-07-15 06:37

import profiles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_profile_art_service_enabled_artservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[profiles.utils.validate_username_format]),
        ),
    ]
