# Generated by Django 5.2.1 on 2025-07-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_profile_username'),
        ('profiles', '0026_profile_allow_mentions'),
    ]

    operations = [
    ]
