# Generated by Django 5.2.1 on 2025-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_merge_20250716_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
