# Generated by Django 5.2.1 on 2025-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_profile_has_seen_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_seen_tutorial',
            new_name='profile_tutorial',
        ),
        migrations.AddField(
            model_name='profile',
            name='wall_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
