# Generated by Django 5.2.1 on 2025-07-17 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emailtemplate_subject'),
        ('organization', '0010_alter_organization_phone_number'),
        ('profiles', '0029_rename_has_seen_tutorial_profile_profile_tutorial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='profile_username_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['bio'], name='profile_bio_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['tools'], name='profile_tools_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['awards'], name='profile_awards_idx'),
        ),
    ]
