# Generated by Django 5.2.1 on 2025-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profile_is_verified_profile_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_required',
            field=models.BooleanField(default=True),
        ),
    ]
