# Generated by Django 5.2.1 on 2025-06-02 14:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Industry Type',
                'verbose_name_plural': 'Industry Types',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('field_name', models.CharField(help_text="Name of the field (e.g., 'Website URL', 'Founded Year', 'Contact Email')", max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('date', 'Date')], default='text', help_text='Type of field determines which value field to use', max_length=10)),
                ('text_value', models.TextField(blank=True, help_text='For TEXT type - stores URLs, emails, phone numbers, descriptions, etc.', null=True)),
                ('image_value', models.ImageField(blank=True, help_text='For IMAGE type fields', null=True, upload_to='organization_profiles/images/')),
                ('file_value', models.FileField(blank=True, help_text='For FILE type fields', null=True, upload_to='organization_profiles/files/')),
                ('date_value', models.DateField(blank=True, help_text='For DATE type fields', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Should this field be visible on public profile?')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which field appears on profile')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about this field', null=True)),
            ],
            options={
                'ordering': ['organization', 'display_order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Types',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='organizatio_city_26475c_idx'), models.Index(fields=['state'], name='organizatio_state_2fa92d_idx'), models.Index(fields=['country'], name='organizatio_country_b5b5a7_idx'), models.Index(fields=['postal_code'], name='organizatio_postal__dade10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('visibility_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organization.address')),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.industrytype')),
            ],
        ),
    ]
