# Generated by Django 5.2.1 on 2025-07-24 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_invites', to='user.role'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofilefield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofilefield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fields', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationtype'),
        ),
        migrations.AddIndex(
            model_name='organizationinvite',
            index=models.Index(fields=['token'], name='organizatio_token_fa2d20_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvite',
            index=models.Index(fields=['email', 'status'], name='organizatio_email_2d5f86_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvite',
            index=models.Index(fields=['expires_at'], name='organizatio_expires_dc0a98_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invite_per_org_email'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='organizatio_organiz_33d05c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user'], name='organizatio_user_id_c040f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'field_name'], name='organizatio_organiz_4bd61f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'display_order'], name='organizatio_organiz_003482_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'is_public'], name='organizatio_organiz_3c27c1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['field_type'], name='organizatio_field_t_f3327a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['text_value'], name='organizatio_text_va_fba16b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['date_value'], name='organizatio_date_va_0f2e07_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationprofilefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'field_name'), name='unique_org_field_name'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_0d3b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_8060eb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_6c2557_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_f21a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry_type'], name='organizatio_industr_5528de_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_organization_name'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_organization_email'),
        ),
    ]
