# Generated by Django 5.2.1 on 2025-06-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofilefield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofilefield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fields', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationtype'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'field_name'], name='organizatio_organiz_4bd61f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'display_order'], name='organizatio_organiz_003482_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['organization', 'is_public'], name='organizatio_organiz_3c27c1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['field_type'], name='organizatio_field_t_f3327a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['text_value'], name='organizatio_text_va_fba16b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofilefield',
            index=models.Index(fields=['date_value'], name='organizatio_date_va_0f2e07_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationprofilefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'field_name'), name='unique_org_field_name'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_0d3b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_8060eb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_6c2557_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_f21a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry_type'], name='organizatio_industr_5528de_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_organization_name'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_organization_email'),
        ),
    ]
