# Generated by Django 5.2.1 on 2025-06-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_position_organizationmember_organizationinvite_and_more'),
        ('user', '0002_alter_permission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='position',
        ),
        migrations.RemoveField(
            model_name='organizationinvite',
            name='position',
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='org_invites', to='user.role'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
