# Generated by Django 5.2.1 on 2025-06-03 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organizationmember_position_and_more'),
        ('user', '0002_alter_permission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinvite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organizationinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invite_per_org_email'),
        ),
    ]
