# Generated by Django 5.2.1 on 2025-06-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='visibility_status',
        ),
    ]
