# Generated by Django 5.2.1 on 2025-06-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_organization_visibility_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
