# Generated by Django 5.2.1 on 2025-06-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_organization_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
