# Generated by Django 5.2.1 on 2025-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('header_content', models.TextField()),
                ('footer_content', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('copy_right_notice', models.TextField()),
            ],
            options={
                'db_table': 'email_configurations',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('footer_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
    ]
