# Generated by Django 5.2.1 on 2025-07-26 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 26, 13, 10, 52, 15234, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
