# Generated by Django 5.2.1 on 2025-06-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='content',
            new_name='main_content',
        ),
    ]
