# Generated by Django 5.2.1 on 2025-06-26 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_content_emailtemplate_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='main_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
