# Generated by Django 5.2.1 on 2025-06-26 07:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailtemplate_main_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='footer_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
