# Generated by Django 5.2.1 on 2026-02-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_hashtag'),
        ('profiles', '0005_profile_is_online_profile_last_seen_profile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(default=None, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HashTagVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.hashtag')),
            ],
            options={
                'unique_together': {('hashtag', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('SPAM', 'Spam / misleading'), ('ABUSE', 'Abusive / harassing'), ('HATE', 'Hate / violent speech'), ('SEXUAL', 'Sexual / explicit'), ('ILLEGAL', 'Illegal activity'), ('FRAUD', 'Fraud / scam'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_report_content_93408d_idx'), models.Index(fields=['reporter', 'created_at'], name='core_report_reporte_858505_idx'), models.Index(fields=['reason'], name='core_report_reason_8c875e_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'reporter', 'reason'), name='one_report_per_reason_per_target_per_reporter')],
            },
        ),
    ]
