# Generated by Django 5.2.1 on 2025-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_upcomingfeature_featurestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(),
        ),
    ]
