# Generated by Django 5.2.1 on 2025-07-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0002_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(help_text='The User (org-admin or individual) who actually created the post.', on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_art_types',
            field=models.ManyToManyField(blank=True, related_name='custom_art_type_posts', to='post.customarttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AddField(
            model_name='mention',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='post.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='post.post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='post.post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='post.post'),
        ),
        migrations.AddField(
            model_name='postview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='post.post'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='post.post'),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_share', to='profiles.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'profile')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['profile', 'status'], name='post_post_profile_6b5e54_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='post_post_slug_010eca_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='hash_tag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='post_commen_post_id_29b25e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='post_commen_parent__8d82d4_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['profile', '-created_at'], name='post_commen_profile_c8c80c_idx'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='post_postre_post_id_37f51a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'profile')},
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'viewed_at'], name='post_postvi_post_id_47b902_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('viewer', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('profile', 'post')},
        ),
    ]
