# Generated by Django 5.2.1 on 2025-07-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_city_post_country_post_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
