# Generated by Django 5.2.1 on 2025-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_gallery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gallery_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
