# Generated by Django 5.2.1 on 2026-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag_display_name_hashtag_slug_alter_hashtag_name_and_more'),
        ('post', '0005_alter_post_title'),
        ('profiles', '0005_profile_is_online_profile_last_seen_profile_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='post_commen_post_id_29b25e_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='post_commen_parent__8d82d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='post_commen_profile_c8c80c_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='original_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private'), ('friends', 'Friends Only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('removed', 'Removed'), ('scheduled', 'Scheduled'), ('draft', 'Draft')], default='published', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='post_commen_post_id_e63791_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='post_commen_parent__be5a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['profile'], name='post_commen_profile_7a4275_idx'),
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
