# Generated by Django 5.2.1 on 2025-07-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_sharepost'),
        ('post', '0005_alter_post_gallery_order'),
    ]

    operations = [
    ]
