# Generated by Django 5.2.1 on 2025-07-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_merge_0004_sharepost_0005_alter_post_gallery_order'),
        ('profiles', '0017_profile_awards_profile_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_share', to='profiles.profile'),
        ),
    ]
