# Generated by Django 5.2.1 on 2025-07-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_sharepost_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('removed', 'Removed'), ('draft', 'Draft')], default='published', max_length=20),
        ),
    ]
