# Generated by Django 5.2.1 on 2025-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_arttype_customarttype_post_art_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=20),
        ),
    ]
