# Generated by Django 5.2.1 on 2025-07-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_postview'),
        ('profiles', '0020_profile_notify_email_profile_view_count_profileview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('viewer', 'post')},
        ),
    ]
