# Generated by Django 5.2.1 on 2025-07-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=20),
        ),
    ]
