# Generated by Django 5.2.1 on 2025-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
