# Generated by Django 5.2.1 on 2025-07-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_title'),
        ('post', '0015_mention'),
    ]

    operations = [
    ]
