# Generated by Django 5.2.1 on 2025-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_0015_alter_post_title_0015_mention'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='hash_tag_name_idx'),
        ),
    ]
