# Generated by Django 5.2.1 on 2025-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_dailyquote_dailyquoteseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquoteseen',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
