# Generated by Django 5.2.1 on 2025-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_dailyquoteseen_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('tag', 'Tag'), ('mention', 'Mention'), ('share', 'Share'), ('post_create', 'Post Create'), ('Event Create', 'event_create')], max_length=20),
        ),
    ]
