# Generated by Django 5.2.1 on 2025-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('tag', 'Tag'), ('mention', 'Mention'), ('share', 'Share'), ('post_create', 'Post Create'), ('event_media', 'Event Media'), ('event_reminder', 'Event Reminder'), ('status change', 'Status Change'), ('event create', 'Event Create'), ('event rsvp', 'Event Rsvp'), ('mentor eligiblity', 'Mentor Eligiblity'), ('Group', 'group')], max_length=20),
        ),
    ]
