# Generated by Django 5.2.1 on 2025-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('tag', 'Tag'), ('mention', 'Mention'), ('share', 'Share'), ('post_create', 'Post Create'), ('event_create', 'Event Create'), ('event_rsvp', 'Event RSVP')], max_length=20),
        ),
    ]
