# Generated by Django 5.2.1 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('expected_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_response', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
