# Generated by Django 5.2.1 on 2025-08-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hashtag'),
        ('group', '0001_initial'),
        ('profiles', '0004_profile_mentor_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='activity_score',
            new_name='avg_engagement',
        ),
        migrations.RemoveField(
            model_name='group',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='group',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='group',
            name='trending_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='group.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='grouppostcomment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='group.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to='profiles.profile')),
            ],
            options={
                'unique_together': {('group', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='GroupActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Group Created'), ('UPDATE', 'Group Updated'), ('DELETE', 'Group Deleted'), ('JOIN', 'Member Joined'), ('LEAVE', 'Member Left'), ('POST_CREATE', 'Post Created'), ('POST_DELETE', 'Post Deleted'), ('POST_UPDATE', 'Post Update'), ('TAG_ADD', 'Hashtag Added'), ('TAG_REMOVE', 'Hashtag Removed'), ('JOIN_REQUEST', 'Join Request'), ('MEMBER_ADD', 'Member add'), ('MEMBER_UPDATE', 'Member update'), ('MEMBER_REMOVE', 'Member remove')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='group.group')),
                ('group_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.groupmember')),
                ('group_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.grouppost')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('member_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.groupjoinrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='group_group_action_5ac9bd_idx')],
            },
        ),
    ]
