# Generated by Django 5.2.1 on 2025-08-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_activity_score_group_avg_engagement_and_more'),
        ('profiles', '0004_profile_mentor_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='recent_activity_score',
            new_name='activity_score',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupactionlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Group Created'), ('UPDATE', 'Group Updated'), ('DELETE', 'Group Deleted'), ('POST_CREATE', 'Post Created'), ('POST_DELETE', 'Post Deleted'), ('POST_UPDATE', 'Post Update'), ('TAG_ADD', 'Hashtag Added'), ('TAG_REMOVE', 'Hashtag Removed'), ('JOIN_REQUEST', 'Join Request'), ('PUBLIC_JOIN', 'Public Join'), ('MEMBER_ADD', 'Member add'), ('MEMBER_UPDATE', 'Member update'), ('MEMBER_REMOVE', 'Member remove')], max_length=50),
        ),
        migrations.CreateModel(
            name='GroupPostFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('hate_speech', 'Hate speech'), ('misinformation', 'Misinformation'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence or dangerous acts'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='group.grouppost')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_flags', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reported_by')},
            },
        ),
    ]
