# Generated by Django 5.2.1 on 2025-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_recent_activity_score_groupmember_activity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
