# Generated by Django 5.2.1 on 2025-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_recent_activity_score_groupmember_activity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
