# Generated by Django 5.2.1 on 2025-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_slug_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show_members',
            field=models.BooleanField(default=False),
        ),
    ]
