# Generated by Django 5.2.1 on 2026-02-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag_display_name_hashtag_slug_alter_hashtag_name_and_more'),
        ('group', '0006_group_show_members'),
        ('profiles', '0005_profile_is_online_profile_last_seen_profile_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tags',
            new_name='hashtags',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='tags',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='announcement_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='group_posts', to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ShareGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='group.grouppost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_shares', to='profiles.profile')),
            ],
            options={
                'unique_together': {('group_post', 'profile')},
            },
        ),
    ]
