# Generated by Django 5.2.1 on 2025-07-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='profile',
        ),
    ]
