# Generated by Django 5.2.1 on 2025-07-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('event', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_hosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_hosted_events', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AddField(
            model_name='eventactivitylog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventactivitylog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='event.EventAttendance', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='event.eventcomment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='event.eventcomment'),
        ),
        migrations.AddField(
            model_name='eventcommentlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventmediacomment',
            name='event_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event.eventmedia'),
        ),
        migrations.AddField(
            model_name='eventmediacomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='event.eventmediacomment'),
        ),
        migrations.AddField(
            model_name='eventmediacomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventmediacommentlike',
            name='event_media_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_media_comment_like', to='event.eventmediacomment'),
        ),
        migrations.AddField(
            model_name='eventmediacommentlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventmedialike',
            name='event_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_like', to='event.eventmedia'),
        ),
        migrations.AddField(
            model_name='eventmedialike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.eventtag'),
        ),
        migrations.AddIndex(
            model_name='eventactivitylog',
            index=models.Index(fields=['event', 'activity_type'], name='event_event_event_i_b46b9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventactivitylog',
            unique_together={('profile', 'event', 'activity_type')},
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('profile', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='eventcommentlike',
            unique_together={('comment', 'profile')},
        ),
    ]
