# Generated by Django 5.2.1 on 2025-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('webinar', 'Webinar'), ('social', 'Social Event'), ('networking', 'Networking'), ('exhibition', 'Exhibition'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
