# Generated by Django 5.2.1 on 2025-07-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_user_event_profile'),
        ('profiles', '0016_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='profile',
            new_name='host',
        ),
        migrations.AddField(
            model_name='event',
            name='co_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_host_organized_events', to='profiles.profile'),
        ),
    ]
