# Generated by Django 5.2.1 on 2025-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
