# Generated by Django 5.2.1 on 2025-07-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventtag_event_inactivated_at_event_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='registered_at',
        ),
    ]
