# Generated by Django 5.2.1 on 2025-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_completion_mail_sent_eventmedia_comments_count_and_more'),
        ('profiles', '0004_profile_mentor_mail_sent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventmediacommentlike',
            constraint=models.UniqueConstraint(fields=('event_media_comment', 'profile'), name='unique_event_media_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='eventmedialike',
            constraint=models.UniqueConstraint(fields=('event_media', 'profile'), name='unique_event_media_like'),
        ),
    ]
