# Generated by Django 5.2.1 on 2025-08-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventmediacommentlike_unique_event_media_comment_like_and_more'),
        ('group', '0002_rename_activity_score_group_avg_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='group.group'),
        ),
    ]
