# Generated by Django 5.2.1 on 2025-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_eventattendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
