# Generated by Django 5.2.1 on 2026-02-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag_display_name_hashtag_slug_alter_hashtag_name_and_more'),
        ('event', '0006_event_group'),
        ('profiles', '0005_profile_is_online_profile_last_seen_profile_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='hashtags',
            field=models.ManyToManyField(related_name='events', to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShareEventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('event_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='event.eventmedia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_media_shares', to='profiles.profile')),
            ],
            options={
                'unique_together': {('event_media', 'profile')},
            },
        ),
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
