# Generated by Django 5.2.1 on 2025-07-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventmedia_is_pinned'),
        ('profiles', '0032_profile_onboarding_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('event_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event.eventmedia')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='event.eventmediacomment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
