# Generated by Django 5.2.1 on 2025-07-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventmediacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='reminder_1st_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='reminder_2nd_sent',
            field=models.BooleanField(default=False),
        ),
    ]
