# Generated by Django 5.2.1 on 2025-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventattendance_reminder_1st_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='reminder_1st_sent',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='reminder_2nd_sent',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.eventtag'),
        ),
    ]
