# Generated by Django 5.2.1 on 2025-07-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventattendance_reminder_1st_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='slug',
        ),
    ]
