# Generated by Django 5.2.1 on 2025-07-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_eventtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_1st_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_2nd_sent',
            field=models.BooleanField(default=False),
        ),
    ]
