# Generated by Django 5.2.1 on 2025-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_eventtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/logo/'),
        ),
    ]
