# Generated by Django 5.2.1 on 2025-07-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_event_logo'),
        ('event', '0011_event_reminder_1st_sent_event_reminder_2nd_sent'),
    ]

    operations = [
    ]
