# Generated by Django 5.2.1 on 2025-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
