# Generated by Django 5.2.1 on 2025-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_event_slug'),
        ('profiles', '0032_profile_onboarding_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_host',
        ),
        migrations.AddField(
            model_name='event',
            name='co_host',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_hosted_events', to='profiles.profile'),
        ),
    ]
