# Generated by Django 5.2.1 on 2025-07-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_event_co_host_event_co_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='co_host',
            new_name='co_hosts',
        ),
    ]
