# Generated by Django 5.2.1 on 2025-07-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_rename_co_host_event_co_hosts'),
        ('profiles', '0032_profile_onboarding_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventMediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('event_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_like', to='event.eventmedia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
