# Generated by Django 5.2.1 on 2025-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_eventmedia_like_count_eventmedialike'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aprove_attendees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('pending', 'Pending'), ('declined', 'Declined')], default='interested', max_length=20),
        ),
    ]
