# Generated by Django 5.2.1 on 2025-07-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_aprove_attendees_alter_eventattendance_status'),
        ('profiles', '0032_profile_onboarding_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMediaCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('eventmediacomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_media_comment_like', to='event.eventmediacomment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
