# Generated by Django 5.2.1 on 2025-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventmediacommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmediacomment',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
