# Generated by Django 5.2.1 on 2025-07-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventmediacomment_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmediacommentlike',
            old_name='eventmediacomment',
            new_name='event_media_comment',
        ),
    ]
