# Generated by Django 5.2.1 on 2025-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role_organization_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('organization', 'Organization'), ('admin', 'System Admin')], default='admin', max_length=15),
        ),
    ]
