# Generated by Django 5.2.1 on 2025-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_permission_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
