# Generated by Django 5.2.1 on 2025-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='art_prompts/images/')),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('use_type', models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag')], max_length=50)),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
