# Generated by Django 5.2.1 on 2025-07-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0025_profile_art_service_enabled_artservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='art_prompts/images/')),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_texts', models.TextField(help_text='AI-generated description and hashtags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_prompts', to='profiles.profile')),
            ],
        ),
    ]
