# Generated by Django 5.2.1 on 2025-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimageprompt',
            name='gpt_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
