# Generated by Django 5.2.1 on 2025-07-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimageprompt',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_prompts', to='profiles.profile'),
        ),
        migrations.CreateModel(
            name='BaseAIPromptDetails',
            fields=[
                ('baseaiconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.baseaiconfig')),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ai.baseaiconfig',),
        ),
        migrations.CreateModel(
            name='EventTagPrompt',
            fields=[
                ('baseaipromptdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.baseaipromptdetails')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tag_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('ai.baseaipromptdetails',),
        ),
    ]
