# Generated by Django 5.2.1 on 2025-07-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaiconfig',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description')], max_length=50),
        ),
        migrations.CreateModel(
            name='EventDescriptionPrompt',
            fields=[
                ('baseaipromptdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.baseaipromptdetails')),
                ('event_data', models.JSONField(help_text='Input event data used to generate description')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_description_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('ai.baseaipromptdetails',),
        ),
    ]
