# Generated by Django 5.2.1 on 2025-07-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_artimageprompt_gpt_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artimageprompt',
            old_name='response_texts',
            new_name='response_text',
        ),
    ]
