# Generated by Django 5.2.1 on 2025-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_response_texts_artimageprompt_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimageprompt',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artimageprompt',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artimageprompt',
            name='total_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
