# Generated by Django 5.2.1 on 2025-07-31 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_baseaiconfig_use_type_eventdescriptionprompt'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdescriptionprompt',
            name='baseaipromptdetails_ptr',
        ),
        migrations.RemoveField(
            model_name='eventtagprompt',
            name='baseaipromptdetails_ptr',
        ),
        migrations.RemoveField(
            model_name='eventdescriptionprompt',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='eventtagprompt',
            name='profile',
        ),
        migrations.CreateModel(
            name='EventDescriptionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('use_type', models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description')], max_length=50)),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('description', models.TextField()),
                ('event_data', models.JSONField(help_text='Input event data used to generate description')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_description_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTagResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('use_type', models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description')], max_length=50)),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('description', models.TextField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tag_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BaseAIPromptDetails',
        ),
        migrations.DeleteModel(
            name='EventDescriptionPrompt',
        ),
        migrations.DeleteModel(
            name='EventTagPrompt',
        ),
    ]
