# Generated by Django 5.2.1 on 2025-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_artimageprompt_input_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='artimageprompt',
            name='gpt_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
