# Generated by Django 5.2.1 on 2025-08-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_eventdescriptionprompt_baseaipromptdetails_ptr_and_more'),
        ('profiles', '0004_profile_mentor_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaiconfig',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description'), ('group_description', 'Group Description')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdescriptionresponse',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description'), ('group_description', 'Group Description')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventtagresponse',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description'), ('group_description', 'Group Description')], max_length=50),
        ),
        migrations.CreateModel(
            name='GroupTagsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('use_type', models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag'), ('event_description', 'Event Description'), ('group_description', 'Group Description')], max_length=50)),
                ('gpt_model', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.TextField(help_text='Prompt or instruction sent to OpenAI')),
                ('description', models.TextField()),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_description_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
