# Generated by Django 5.2.1 on 2025-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_baseaiconfig_alter_artimageprompt_gpt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaiconfig',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
