# Generated by Django 5.2.1 on 2025-07-18 08:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_baseaiconfig_use_type'),
        ('profiles', '0031_profile_is_verified_profile_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAIPromptDetails',
            fields=[
                ('baseaiconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.baseaiconfig')),
                ('response', models.TextField(help_text='AI-generated whole response')),
                ('response_text', models.TextField(help_text='AI-generated description and hashtags')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ai.baseaiconfig',),
        ),
        migrations.AddField(
            model_name='baseaiconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 18, 8, 24, 57, 651901, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseaiconfig',
            name='inactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseaiconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseaiconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventTagPrompt',
            fields=[
                ('baseaipromptdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.baseaipromptdetails')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tag_prompts', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('ai.baseaipromptdetails',),
        ),
    ]
