# Generated by Django 5.2.1 on 2025-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_baseaipromptdetails_baseaiconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaiconfig',
            name='use_type',
            field=models.CharField(choices=[('image_description', 'Image Description'), ('event_tag', 'Event Tag')], max_length=50),
        ),
    ]
